apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: locales
spec:
  version: 8.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
kind: Service
apiVersion: v1
metadata:
  name: locales
spec:
  selector:
    app: locales-es-http
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer