apiVersion: v1
kind: Pod
metadata:
  name: dind
spec:
  containers:
    - name: dind-daemon
      image: ghcr.io/gantrycd/image-builder:v0.0.3
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: GIT_REPO
          value: "https://github.com/xpadev-net/video_host_frontend"
        - name: IMAGE_NAME
          value: "video_host_frontend"
        - name: IMAGE_TAG
          value: "latest"
        - name: DOCKER_REGISTRY
          value: "ghcr.io"
        - name: DOCKER_REGISTRY_USER
          value: "gantrycd"
        - name: DOCKER_REGISTRY_PASSWORD
          value: hoge
      resources:
        requests:
          cpu: 20m
          memory: 512Mi
      securityContext:
        privileged: true