apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault.yml
  - external-secrets.yml
  - cloudflared-tunnel.yml
  - signoz.yml
  - tidb-operator.yml
  - tidb-crd.yml
  - tidb-cluster.yml
  - tidb-dashboard.yml
