apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph-cluster
    targetRevision: v1.17.1
    helm:
      valuesObject:
        storage:
          useAllNodes: false
          useAllDevices: false
          nodes:
            - name: "k8s-tky-1"
              devices:
                - name: "sdb1"
            - name: "k8s-tky-2"
              devices:
                - name: "sdb1"
            - name: "k8s-osk-2"
              devices:
                - name: "sdb1"
            - name: "k8s-osk-3"
              devices:
                - name: "sdb1"
            - name: "k8s-osk-4"
              devices:
                - name: "sdb1"
        cephBlockPools:
          - name: "ceph-blockpool"
            storageClass:
              isDefault: false
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
