apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-host-api-deployment
  namespace: video-host
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: video-host-api
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: video-host-api
    spec:
      containers:
        - name: video-host-api
          image: ghcr.io/xpadev-net/video-host-api:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: video-host-api
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 180
            periodSeconds: 10
          resources:
            limits:
              memory: 2Gi
              cpu: "2"
            requests:
              memory: 1Gi
              cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: video-host-api
  namespace: video-host
spec:
  selector:
    app: video-host-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
