apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-host-deployment
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: video-host
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: video-host
    spec:
      containers:
      - name: video-host
        image: ghcr.io/xpadev-net/video_host_frontend:v0.0.13
        ports:
          - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: video-host
                key: NEXT_PUBLIC_API_ENDPOINT
          - name: NEXT_PUBLIC_SITE_NAME
            valueFrom:
              configMapKeyRef:
                name: video-host
                key: NEXT_PUBLIC_SITE_NAME
          - name: NEXT_PUBLIC_ENABLE_COMMENTS
            value: "true"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          failureThreshold: 180
          periodSeconds: 10
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: video-host
spec:
  selector:
    app: video-host
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.11.1
