apiVersion: v1
kind: Pod
metadata:
  name: video-host
  labels:
    app: video-host
spec:
  containers:
    - name: video-host
      image: ghcr.io/xpadev-net/video_host:v0.0.4
      ports:
        - containerPort: 3000
  imagePullSecrets:
    - name: ghcr-login-secret
---
kind: Service
apiVersion: v1
metadata:
  name: video-host
spec:
  selector:
    app: video-host
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
