apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-host-deployment
  namespace: video-host
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: video-host
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: video-host
    spec:
      containers:
        - name: video-host
          image: ghcr.io/xpadev-net/video_host_frontend:v0.0.33
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_ENABLE_COMMENTS
              value: "true"
          envFrom:
            - configMapRef:
                name: video-host
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            failureThreshold: 180
            periodSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: video-host
  namespace: video-host
spec:
  selector:
    app: video-host
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
