apiVersion: v1
kind: Pod
metadata:
  name: video_host
  labels:
    app: video_host
spec:
  containers:
    - name: video_host
      image: ghcr.io/xpadev-net/video_host:v0.0.2
      ports:
      - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: video_host
spec:
  selector:
    app: video_host
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer