apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    chart: tenant
    targetRevision: 7.0.1
    helm:
      parameters:
        - name: tenant.name
          value: tenant
        - name: tenant.pools[0].name
          value: "pool"
        - name: tenant.pools[0].servers
          value: "2"
        - name: tenant.pools[0].volumesPerServer
          value: "1"
        - name: tenant.pools[0].storageClassName
          value: "minio-storage"
        - name: tenant.pools[0].size
          value: "32Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
