apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    chart: tenant
    targetRevision: 7.0.1
    helm:
      valueFiles:
        - https://github.com/xpadev-net/k8s/blob/master/minio/tenant/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
