apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    chart: tenant
    targetRevision: 7.0.1
    helm:
      values: |
        tenant:
          name: tenant
          image:
            repository: quay.io/minio/minio
            tag: RELEASE.2025-04-03T14-56-28Z
            pullPolicy: IfNotPresent
          imagePullSecret: {}
          initContainers: []
          scheduler: {}
          configuration:
            name: myminio-env-configuration
          configSecret:
            name: myminio-env-configuration
            accessKey: minio
            secretKey: minio123
            #existingSecret: true
          poolsMetadata:
            annotations: {}
            labels: {}
          pools:
            - servers: 2
              name: pool-0
              volumesPerServer: 2
              size: 32Gi
              storageAnnotations: {}
              storageLabels: {}
              annotations: {}
              labels: {}
              tolerations: []
              nodeSelector: {}
              affinity: {}
              resources: {}
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                fsGroupChangePolicy: "OnRootMismatch"
                runAsNonRoot: true
              containerSecurityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              topologySpreadConstraints: []
          mountPath: /export
          subPath: /data
          metrics:
            enabled: false
            port: 9000
            protocol: http
          certificate:
            externalCaCertSecret: []
            externalCertSecret: []
            requestAutoCert: true
            certConfig: {}
          features:
            bucketDNS: false
            domains: {}
            enableSFTP: false
          buckets: []
          users: []
          podManagementPolicy: Parallel
          liveness: {}
          readiness: {}
          startup: {}
          lifecycle: {}
          exposeServices: {}
          serviceAccountName: ""
          prometheusOperator: false
          logging: {}
          serviceMetadata: {}
          env: []
          priorityClassName: ""
          additionalVolumes: []
          additionalVolumeMounts: []
        ingress:
          api:
            enabled: false
            ingressClassName: ""
            labels: {}
            annotations: {}
            tls: []
            host: minio.local
            path: /
            pathType: Prefix
          console:
            enabled: true
            ingressClassName: ""
            labels: {}
            annotations: {}
            tls: []
            host: minio-console.local
            path: /
            pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
