apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-rule-default
  namespace: default
spec:
  rules:
  - host: video-host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: video-host
            port:
              number: 3000
  - host: dashy
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashy
            port:
              number: 8080
  ingressClassName: nginx