apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: video-host
      http:
        paths:
          - backend:
              service:
                name: video-host
                port:
                  number: 80
            path: /
            pathType: Prefix