apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-agent
  namespace: zabbix
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
      - hostaccess
      - hostnetwork
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zabbix-agent
  namespace: zabbix
subjects:
  - kind: ServiceAccount
    name: zabbix-agent
roleRef:
  kind: Role
  name: zabbix-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-agent
  namespace: zabbix
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web-http
    - port: 443
      targetPort: 8443
      name: web-https
  selector:
    name: zabbix-web
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 162
      targetPort: 1162
      protocol: UDP
      name: snmp-trap
  selector:
    name: zabbix-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 162
      targetPort: 1162
      protocol: UDP
      name: snmp-trap
  selector:
    name: zabbix-proxy-sqlite3
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 162
      targetPort: 1162
      protocol: UDP
      name: snmp-trap
  selector:
    name: zabbix-proxy-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10052
      targetPort: 10052
      name: zabbix-jmx
  selector:
    name: zabbix-java-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10053
      targetPort: 10053
      name: zabbix-web-svc
  selector:
    name: zabbix-web-service
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10050
      targetPort: 10050
      name: zabbix-agent
  selector:
    name: zabbix-agent
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web-http
            - containerPort: 8443
              name: web-https
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: ZBX_SERVER_NAME
              value: "Zabbix Kubernetes"
            - name: PHP_TZ
              value: "Europe/Riga"
            - name: DB_SERVER_HOST
              value: "basic-tidb.tidb-cluster-ceph.svc.cluster.local"
            - name: DB_SERVER_PORT
              value: "4000"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: ZBX_DB_ENCRYPTION
              value: "true"
            - name: ZBX_DB_VERIFY_HOST
              value: "false"
            #          - name: ZBX_HISTORYSTORAGEURL
            #            value: ""
            #          - name: ZBX_HISTORYSTORAGETYPES
            #            value: ""
            #          - name: ZBX_MAXEXECUTIONTIME
            #            value: ""
            #          - name: ZBX_MEMORYLIMIT
            #            value: ""
            #          - name: ZBX_POSTMAXSIZE
            #            value: ""
            #          - name: ZBX_UPLOADMAXFILESIZE
            #            value: ""
            #          - name: ZBX_MAXINPUTTIME
            #            value: ""
            #          - name: ZBX_SESSION_NAME
            #            value: ""
            #          - name: DB_DOUBLE_IEEE754
            #            value: "true"
            - name: ZBX_SSO_SETTINGS
              value: "[]"
            - name: ENABLE_WEB_ACCESS_LOG
              value: "true"
            - name: DEBUG_MODE
              value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-server
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      volumes:
        - name: zabbix-snmptraps
          emptyDir: {}
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10051
              protocol: TCP
              name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: DB_SERVER_HOST
              value: "basic-tidb.tidb-cluster-ceph.svc.cluster.local"
            - name: DB_SERVER_PORT
              value: "4000"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DATABASE
              value: "mysql-server"

            - name: ZBX_DBTLSCONNECT
              value: "required"
            - name: ZBX_HISTORYSTORAGEDATEINDEX
              value: "1"
            - name: ZBX_STARTREPORTWRITERS
              value: "3"
            - name: ZBX_WEBSERVICEURL
              value: "http://zabbix-web-service:10053/report"
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
            - name: ZBX_JAVAGATEWAY
              value: "zabbix-java-gateway"
            - name: ZBX_JAVAGATEWAYPORT
              value: "10052"
            - name: ZBX_STARTJAVAPOLLERS
              value: "5"
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
            - name: ZBX_TIMEOUT
              value: "4"
            - name: ZBX_LOGSLOWQUERIES
              value: "3000"
            - name: DEBUG_MODE
              value: "false"
          volumeMounts:
            - name: zabbix-snmptraps
              mountPath: "/var/lib/zabbix/snmptraps"
              readOnly: true
          startupProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 40
          securityContext:
            capabilities: {}
            privileged: false
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1162
              protocol: UDP
              name: snmp-trap
          volumeMounts:
            - name: zabbix-snmptraps
              mountPath: /var/lib/zabbix/snmptraps/
              readOnly: false
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-proxy-sqlite3
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-proxy-sqlite3
        app: zabbix
    spec:
      volumes:
        - name: proxy-sqlite-data
          emptyDir: {}
      containers:
        - name: zabbix-proxy-sqlite3
          image: zabbix/zabbix-proxy-sqlite3:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10051
              protocol: TCP
              name: zabbix-trapper
          startupProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 40
          livenessProbe:
            tcpSocket:
              port: 10051
            timeoutSeconds: 3
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: ZBX_PROXYMODE
              value: "1"
            - name: ZBX_HOSTNAME
              value: "zabbix-proxy-sqlite"
            - name: ZBX_ENABLEREMOTECOMMANDS
              value: "0"
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
            - name: ZBX_JAVAGATEWAY
              value: "zabbix-java-gateway"
            - name: ZBX_JAVAGATEWAYPORT
              value: "10052"
            - name: ZBX_STARTJAVAPOLLERS
              value: "5"
            - name: ZBX_TIMEOUT
              value: "4"
            - name: DEBUG_MODE
              value: "false"
          volumeMounts:
            - mountPath: "/var/lib/zabbix/db_data"
              name: proxy-sqlite-data
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-mysql
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: zabbix-proxy-mysql
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-proxy-mysql
        app: zabbix
    spec:
      containers:
        - name: zabbix-proxy-mysql
          image: zabbix/zabbix-proxy-mysql:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10051
              protocol: TCP
              name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: DB_SERVER_HOST
              value: "basic-tidb.tidb-cluster-ceph.svc.cluster.local"
            - name: DB_SERVER_PORT
              value: "4000"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DATABASE
              value: "zabbix_proxy"
            - name: ZBX_DBTLSCONNECT
              value: "required"
            - name: ZBX_PROXYMODE
              value: "0"
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: ZBX_HOSTNAME
              value: "zabbix-proxy-mysql"
            - name: ZBX_ENABLEREMOTECOMMANDS
              value: "0"
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: "true"
            - name: ZBX_JAVAGATEWAY
              value: "zabbix-java-gateway"
            - name: ZBX_JAVAGATEWAYPORT
              value: "10052"
            - name: ZBX_STARTJAVAPOLLERS
              value: "5"
            - name: ZBX_TIMEOUT
              value: "4"
            - name: DEBUG_MODE
              value: "false"
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
    tier: java
  namespace: zabbix
spec:
  selector:
    matchLabels:
      name: zabbix-java-gateway
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-java-gateway
        app: zabbix
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10052
              protocol: TCP
              name: zabbix-java
          livenessProbe:
            tcpSocket:
              port: 10052
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
            - name: ZBX_START_POLLERS
              value: "5"
            - name: ZBX_TIMEOUT
              value: "3"
            - name: ZBX_DEBUGLEVEL
              value: "info"
            - name: JAVA_OPTIONS
              value: ""
            - name: DEBUG_MODE
              value: "false"
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-service
  labels:
    app: zabbix
    tier: web-service
  namespace: zabbix
spec:
  selector:
    matchLabels:
      name: zabbix-web-service
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-web-service
        app: zabbix
    spec:
      containers:
        - name: zabbix-web-service
          image: zabbix/zabbix-web-service:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 10053
              protocol: TCP
              name: zabbix-web-svc
          livenessProbe:
            tcpSocket:
              port: 10053
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
            - name: ZBX_ALLOWEDIP
              value: "0.0.0.0/0"
            - name: ZBX_LISTENPORT
              value: "10053"
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_TIMEOUT
              value: "3"
            - name: ZBX_TLSACCEPT
              value: ""
            - name: ZBX_TLSCAFILE
              value: ""
            - name: ZBX_TLSCERTFILE
              value: ""
            - name: ZBX_TLSKEYFILE
              value: ""
            - name: DEBUG_MODE
              value: "false"
          securityContext:
            capabilities: {}
            privileged: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: agent
  namespace: zabbix
spec:
  selector:
    matchLabels:
      name: zabbix-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      automountServiceAccountToken: true
      serviceAccountName: zabbix-agent
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-7.4-latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 54Mi
            requests:
              cpu: 100m
              memory: 54Mi
          ports:
            - containerPort: 10050
              name: zabbix-agent
          livenessProbe:
            tcpSocket:
              port: 10050
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_DENYKEY
              value: "system.run[*]"
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZBX_REFRESHACTIVECHECKS
              value: "120"
            - name: DEBUG_MODE
              value: "3"
          securityContext:
            capabilities: {}
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - name: dev-volume
              mountPath: /node/dev
            - name: procfs-volume
              readOnly: true
              mountPath: /node/proc
            - name: boot-volume
              readOnly: true
              mountPath: /node/boot
            - name: run-volume
              mountPath: /node/run
            - name: var-run-volume
              mountPath: /node/var/run
      volumes:
        - name: dev-volume
          hostPath:
            path: /dev
            type: ""
        - name: procfs-volume
          hostPath:
            path: /proc
            type: ""
        - name: boot-volume
          hostPath:
            path: /boot
            type: ""
        - name: run-volume
          hostPath:
            path: /run
            type: ""
        - name: var-run-volume
          hostPath:
            path: /var/run
            type: ""
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: v1
kind: List
metadata:
  namespace: zabbix
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: db-secret
      namespace: zabbix
    data:
      db-root-pass: "c29tZV90ZXN0X3Bhc3M="
      db-zbx-user: "emFiYml4"
      db-zbx-pass: "emJ4X3Bhc3N3b3Jk"
