apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v3.4.1
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v2.22.1
  serviceMonitorSelector: {}
  remoteWrite:
    - url: "https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push"
      basicAuth:
        username:
          name: prometheus-secret
          key: username
        password:
          name: prometheus-secret
          key: password
  replicaExternalLabelName: "__replica__"
  externalLabels:
    cluster: "local-k8s"
