apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator-application
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: 26.2.5
  syncPolicy:
    automated: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
