apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tidb-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.pingcap.org/
    chart: tidb-operator
    targetRevision: v1.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: tidb-admin
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
