apiVersion: v1
kind: Pod
metadata:
  name: geekcamp2023-vol5-backend
  labels:
    app: geekcamp2023-vol5-backend
spec:
  containers:
    - name: geekcamp2023-vol5-backend
      image: ghcr.io/geekcamp2023-vol5-team31/backend:v0.0.7
      ports:
        - containerPort: 8000
      env:
        - name: HOST
          value: geekcamp2023-vol5-backend
        - name: ORIGIN
          value: https://warikanji.xpadev.net
  imagePullSecrets:
    - name: ghcr-login-secret
---
kind: Service
apiVersion: v1
metadata:
  name: geekcamp2023-vol5-backend
spec:
  selector:
    app: geekcamp2023-vol5-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
