apiVersion: "v1"
kind: "Namespace"
metadata: 
  name: "nextcloud"
  labels: 
    name: "nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
  name: next-config-pvc
  namespace: "nextcloud"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
  name: next-data-pvc
  namespace: "nextcloud"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
  name: next-apps-pvc
  namespace: "nextcloud"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-app-deployment
  namespace: "nextcloud"
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud-app
  replicas: 1 
  template: 
    metadata:
      labels:
        app: nextcloud-app
    spec:
      containers:
      - name: nextcloud-app
        image: nextcloud
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - mountPath: "/var/www/html/config"
            name: next-config
          - mountPath: "/var/www/html/data"
            name: next-data
          - mountPath: "/var/www/html/custom_apps"
            name: next-apps
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "0.5"
      volumes:
        - name: next-config
          persistentVolumeClaim:
            claimName: next-config-pvc
        - name: next-data
          persistentVolumeClaim:
            claimName: next-data-pvc
        - name: next-apps
          persistentVolumeClaim:
            claimName: next-apps-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-app
  namespace: "nextcloud"
spec:
  selector:
    app: nextcloud-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer