apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-node-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-node-monitor-binding
subjects:
  - kind: ServiceAccount
    name: k8s-node-monitor
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-node-monitor-job
  namespace: default
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  timezone: Asia/Tokyo
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k8s-node-monitor
              image: ghcr.io/xpadev/k8s-node-monitor:v0.0.4
              command:
                [
                  "./k8s-node-monitor",
                  "--config",
                  "/etc/config/config.yml",
                  "--restart",
                ]
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
          volumes:
            - name: config-volume
              configMap:
                name: k8s-node-monitor-config
          restartPolicy: Never
      backoffLimit: 1
