apiVersion: v1
kind: Pod
metadata:
  name: geekmeet-backend
  labels:
    app: geekmeet-backend
spec:
  containers:
    - name: geekmeet-backend
      image: ghcr.io/xpadev-net/geekmeet_backend:v0.0.3
      ports:
        - containerPort: 3000
      env:
        - name: ExpressPort
          value: 3000
        - name: ExpressCorsHost
          value: https://geekmeet.xpadev.net
  imagePullSecrets:
    - name: ghcr-login-secret
---
kind: Service
apiVersion: v1
metadata:
  name: geekmeet-backend
spec:
  selector:
    app: geekmeet-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.11.5