apiVersion: v1
kind: Pod
metadata:
  name: geekmeet-frontend
  labels:
    app: geekmeet-frontend
spec:
  containers:
    - name: geekmeet-frontend
      image: ghcr.io/xpadev-net/geekmeet_frontend:v0.0.5
      ports:
        - containerPort: 3000
      env:
        - name: NEXT_PUBLIC_API_ENDPOINT
          value: https://geekmeet-backend.xpadev.net
  imagePullSecrets:
    - name: ghcr-login-secret
---
kind: Service
apiVersion: v1
metadata:
  name: geekmeet-frontend
spec:
  selector:
    app: geekmeet-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.11.4