apiVersion: apps/v1
kind: Deployment
metadata:
  name: geekmeet-frontend-deployment
  namespace: geekmeet
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: geekmeet-frontend
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: geekmeet-frontend
    spec:
      containers:
        - name: geekmeet-frontend
          image: ghcr.io/xpadev-net/geekmeet_frontend:v0.0.10
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_ENDPOINT
              value: https://geekmeet-backend.xpadev.net
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 600
            periodSeconds: 10
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m
---
kind: Service
apiVersion: v1
metadata:
  name: geekmeet-frontend
  namespace: geekmeet
spec:
  selector:
    app: geekmeet-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.11.4
