apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  template:
    spec:
      volumes:
        - name: creds
          secret:
            # Create the secret before sync if not managed by another controller:
            # kubectl create secret generic tky-tunnel-credentials \
            # --namespace cloudflared \
            # --from-file=credentials.json=/Users/yourusername/.cloudflared/<tunnel ID>.json
            secretName: tky-tunnel-credentials
