server:
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "http://tky-vault-chart-0.tky-vault-chart-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://tky-vault-chart-1.tky-vault-chart-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://tky-vault-chart-2.tky-vault-chart-internal:8200"
          }
        }

        service_registration "kubernetes" {}
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: rook-ceph-block
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

ui:
  enabled: true
  activeVaultPodOnly: true
  serviceType: LoadBalancer
  loadBalancerIP: 10.153.11.20
