apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tky-vault-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.33.0
      helm:
        valueFiles:
          - $values/argocd/apps/tky/vault-values.yaml
    - repoURL: https://github.com/xpadev-net/k8s.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: tky-vault-chart-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
