apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  namespace: mysql-cluster
spec:
  secretName: mysql-cluster-secret
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-cluster
