apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mysql.github.io/mysql-operator/
    chart: mysql-innodbcluster
    targetRevision: 2.2.3
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-innodbcluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false
