kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "postgres"
  namespace: "postgres-operator"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 2
  enableMasterLoadBalancer: true
  enableConnectionPooler: true
  enableMasterPoolerLoadBalancer: true
  maintenanceWindows:
  volume:
    size: "10Gi"

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
