apiVersion: apps/v1
kind: Deployment
metadata:
  name: u22procon-23
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: u22procon-23-app
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: u22procon-23-app
    spec:
      containers:
      - name: u22procon-23-app
        image: ghcr.io/xpadev-net/video_host_frontend:v0.0.16
        ports:
          - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_ENDPOINT
            value: https://u22procon23-api.xpadev.net/v23
          - name: NEXT_PUBLIC_SITE_NAME
            value: u22procon-23
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          failureThreshold: 180
          periodSeconds: 10
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: u22procon-23-svc
spec:
  selector:
    app: u22procon-23-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
