apiVersion: v1
kind: Pod
metadata:
  name: dashy
  labels:
    app: dashy
spec:
  containers:
    - name: dashy
      image: lissy93/dashy:latest
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: dashy
spec:
  selector:
    app: dashy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
