apiVersion: apps/v1
kind: Deployment
metadata:
  name: geekcamp2023-vol9
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: geekcamp2023-vol9-frontend
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: geekcamp2023-vol9-frontend
    spec:
      containers:
        - name: geekcamp2023-vol9-frontend
          image: ghcr.io/geekcamp2023-vol9-team30/frontend:v0.0.2
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 180
            periodSeconds: 10
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
            requests:
              memory: 1Gi
              cpu: "0.5"
---
kind: Service
apiVersion: v1
metadata:
  name: geekcamp2023-vol9-svc
spec:
  selector:
    app: geekcamp2023-vol9-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
